"""evenv marks created_at

Revision ID: 4449a63cda23
Revises: 149b4fdcc1c7
Create Date: 2024-11-29 15:37:28.542308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4449a63cda23"
down_revision: Union[str, None] = "149b4fdcc1c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_marks",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Moscow', NOW())"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_marks", "created_at")
    # ### end Alembic commands ###
