"""model update

Revision ID: f4a15b1f98c8
Revises: 7c331afcec43
Create Date: 2024-11-28 19:20:04.692350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4a15b1f98c8"
down_revision: Union[str, None] = "7c331afcec43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "events", "users", ["creator_id"], ["id"])
    op.add_column("users", sa.Column("stars", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "stars")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_column("events", "creator_id")
    # ### end Alembic commands ###
