"""detele token table

Revision ID: 4f2bb6d32cea
Revises: 0b32a467dab0
Create Date: 2024-11-27 11:54:14.898996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f2bb6d32cea"
down_revision: Union[str, None] = "0b32a467dab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="tokens_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="tokens_pkey"),
        sa.UniqueConstraint("token", name="tokens_token_key"),
    )
    # ### end Alembic commands ###
