"""event

Revision ID: 7c331afcec43
Revises: 4f2bb6d32cea
Create Date: 2024-11-27 12:38:53.962140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c331afcec43"
down_revision: Union[str, None] = "4f2bb6d32cea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column(
            "type",
            sa.Enum("MEETING", "REPETITION", "PROMOVEMENT", name="eventtype"),
            nullable=False,
        ),
        sa.Column(
            "start_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Moscow', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "end_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Moscow', NOW())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
