"""event stars

Revision ID: 377ce85e763c
Revises: 4449a63cda23
Create Date: 2024-11-29 16:27:21.882467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "377ce85e763c"
down_revision: Union[str, None] = "4449a63cda23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_stars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Moscow', NOW())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_stars_event_user"),
    )
    op.drop_constraint("uq_event_user", "event_marks", type_="unique")
    op.create_unique_constraint(
        "uq_marks_event_user", "event_marks", ["event_id", "user_id"]
    )
    op.drop_column("users", "stars")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("stars", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("uq_marks_event_user", "event_marks", type_="unique")
    op.create_unique_constraint("uq_event_user", "event_marks", ["event_id", "user_id"])
    op.drop_table("event_stars")
    # ### end Alembic commands ###
